provider:
  name: openfaas

functions:
  myfunc:
    lang: node
    handler: ./myfunc
    image: desno365/myfunc:latest

  myfunc12:
    lang: node12
    handler: ./myfunc12
    image: desno365/myfunc12:latest

  myfunc14:
    lang: node14
    handler: ./myfunc14
    image: desno365/myfunc14:latest

  redis-get:
    lang: node14
    handler: ./redis-get
    image: desno365/redis-get:latest
    environment_file:
      - redis-environment-variables.yml

  redis-set:
    lang: node14
    handler: ./redis-set
    image: desno365/redis-set:latest
    environment_file:
      - redis-environment-variables.yml

