provider:
  name: openfaas

functions:
  myfunc:
    lang: node
    handler: ./myfunc
    image: desno365/myfunc:latest
    limits:
      memory: 256Mi
      cpu: 1000m
    requests:
      memory: 4Mi
      cpu: 0m

  myfunc12:
    lang: node12
    handler: ./myfunc12
    image: desno365/myfunc12:latest
    limits:
      memory: 256Mi
      cpu: 1000m
    requests:
      memory: 4Mi
      cpu: 0m

  myfunc14:
    lang: node14
    handler: ./myfunc14
    image: desno365/myfunc14:latest
    limits:
      memory: 256Mi
      cpu: 1000m
    requests:
      memory: 4Mi
      cpu: 0m

  redis-get:
    lang: node14
    handler: ./redis-get
    image: desno365/redis-get:latest
    environment_file:
      - redis-environment-variables.yml
    limits:
      memory: 256Mi
      cpu: 1000m
    requests:
      memory: 4Mi
      cpu: 0m

  redis-set:
    lang: node14
    handler: ./redis-set
    image: desno365/redis-set:latest
    environment_file:
      - redis-environment-variables.yml
    limits:
      memory: 256Mi
      cpu: 1000m
    requests:
      memory: 4Mi
      cpu: 0m

