provider:
  name: openfaas

configuration:
  copy:
    - ./common

functions:
  iot-data-reduction:
    lang: node14
    handler: ./iot-data-reduction
    image: desno365/iot-data-reduction:latest
    copy-common:
      - ./common/
    limits:
      memory: 256Mi
      cpu: 1000m
    requests:
      memory: 4Mi
      cpu: 0m

