provider:
  name: openfaas

configuration:
  copy:
    - ./common

functions:
  cron-tester:
    lang: node14
    handler: ./cron-tester
    image: desno365/cron-tester:latest
    copy-common:
      - ./common/
    limits:
      memory: 256Mi
      cpu: 1000m
    requests:
      memory: 4Mi
      cpu: 0m
    annotations:
      topic: cron-function
      schedule: "*/2 * * * *"

  edge-db-data-receiver:
    lang: node14
    handler: ./edge-db-data-receiver
    image: desno365/edge-db-data-receiver:latest
    copy-common:
      - ./common/
    limits:
      memory: 256Mi
      cpu: 1000m
    requests:
      memory: 4Mi
      cpu: 0m

  iot-data-reduction:
    lang: node14
    handler: ./iot-data-reduction
    image: desno365/iot-data-reduction:latest
    copy-common:
      - ./common/
    limits:
      memory: 256Mi
      cpu: 1000m
    requests:
      memory: 4Mi
      cpu: 0m


  get-less-crowded-path:
    lang: node14
    handler: ./get-less-crowded-path
    image: desno365/get-less-crowded-path
    copy-common:
      - ./common/
    limits:
      memory: 256Mi
      cpu: 1000m
    requests:
      memory: 4Mi
      cpu: 0m

  video-footage-receiver:
    lang: node14
    handler: ./video-footage-receiver
    image: desno365/video-footage-receiver
    copy-common:
      - ./common/
    limits:
      memory: 256Mi
      cpu: 1000m
    requests:
      memory: 4Mi
      cpu: 0m


  search-analytics-data-receiver:
    lang: node14
    handler: ./search-analytics-data-receiver
    image: desno365/search-analytics-data-receiver
    copy-common:
      - ./common/
    limits:
      memory: 256Mi
      cpu: 1000m
    requests:
      memory: 4Mi
      cpu: 0m

  search-analytics-performer:
    lang: node14
    handler: ./search-analytics-performer
    image: desno365/search-analytics-performer
    copy-common:
      - ./common/
    limits:
      memory: 256Mi
      cpu: 1000m
    requests:
      memory: 4Mi
      cpu: 0m
